"""SQLAlchemy models used for operational persistence and audit logging."""

from sqlalchemy import Boolean, Column, DateTime, Float, Integer, JSON, String, func

from app.db.session import Base


class User(Base):
    """Database record that stores local template users for bearer-token authentication."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(64), nullable=False, unique=True, index=True)
    password_hash = Column(String(256), nullable=False)
    role = Column(String(32), nullable=False, index=True)
    is_active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())


class TradeAuditLog(Base):
    """Database record that stores a timeline of trade-processing events for observability and compliance."""

    __tablename__ = "trade_audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(16), nullable=False, index=True)
    status = Column(String(64), nullable=False, index=True)
    detail = Column(String(512), nullable=False)
    metadata_json = Column(JSON, nullable=False, default=dict)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())


class StrategyRun(Base):
    """Database record that captures the exact output of one strategy evaluation for later analysis."""

    __tablename__ = "strategy_runs"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(16), nullable=False, index=True)
    timeframe = Column(String(32), nullable=False)
    short_window = Column(Integer, nullable=False)
    long_window = Column(Integer, nullable=False)
    action = Column(String(16), nullable=False)
    confidence = Column(Float, nullable=False)
    reason = Column(String(512), nullable=False)
    metadata_json = Column(JSON, nullable=False, default=dict)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())


class TradeOrder(Base):
    """Database record that tracks orders generated by the platform whether simulated or live."""

    __tablename__ = "trade_orders"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(16), nullable=False, index=True)
    action = Column(String(16), nullable=False)
    quantity = Column(Integer, nullable=False)
    status = Column(String(32), nullable=False, index=True)
    requested_price = Column(Float, nullable=False)
    broker_order_id = Column(String(64), nullable=True, index=True)
    dry_run = Column(Boolean, nullable=False, default=True)
    metadata_json = Column(JSON, nullable=False, default=dict)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())


class Position(Base):
    """Database record that stores the platform's internal view of symbol exposure."""

    __tablename__ = "positions"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(16), nullable=False, index=True, unique=True)
    side = Column(String(16), nullable=False)
    quantity = Column(Integer, nullable=False)
    average_price = Column(Float, nullable=False)
    metadata_json = Column(JSON, nullable=False, default=dict)
    updated_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())


class ReconciliationRun(Base):
    """Database record that stores the outcome of one broker reconciliation attempt."""

    __tablename__ = "reconciliation_runs"

    id = Column(Integer, primary_key=True, index=True)
    status = Column(String(32), nullable=False, index=True)
    source = Column(String(32), nullable=False)
    checked_symbols = Column(Integer, nullable=False)
    mismatched_symbols = Column(Integer, nullable=False)
    detail = Column(String(512), nullable=False)
    metadata_json = Column(JSON, nullable=False, default=dict)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
