"""Typed request, response, and domain models used by trading workflows."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class SignalAction(str, Enum):
    """Allowed trading actions generated by the strategy engine so services stay type-safe."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TradeLifecycleStatus(str, Enum):
    """High-level processing states used for audit logging and operational reporting."""

    RECEIVED = "RECEIVED"
    STRATEGY_EVALUATED = "STRATEGY_EVALUATED"
    RISK_APPROVED = "RISK_APPROVED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"


class OrderStatus(str, Enum):
    """Normalized order states used for internal persistence and broker reporting."""

    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    SIMULATED = "SIMULATED"
    FAILED = "FAILED"


class PositionSide(str, Enum):
    """Represents whether a tracked position is long or short."""

    LONG = "LONG"
    SHORT = "SHORT"


class TradeSignalRequest(BaseModel):
    """Request payload describing the symbol, strategy windows, quantity, and execution mode."""

    symbol: str = Field(..., min_length=1, max_length=10)
    timeframe: str = Field(default="1Min")
    short_window: int = Field(default=5, ge=2, le=100)
    long_window: int = Field(default=20, ge=3, le=200)
    quantity: int = Field(default=1, ge=1)
    dry_run: bool = Field(default=True)


class MarketBar(BaseModel):
    """Internal market-bar model that shields the rest of the app from raw provider SDK objects."""

    close: float
    timestamp: str


class StrategyDecision(BaseModel):
    """Normalized strategy decision that travels from the strategy layer into risk and execution."""

    action: SignalAction
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    reason: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class ExecutionResult(BaseModel):
    """Normalized execution response for dry runs, paper trading, or live broker submission."""

    status: str
    broker_order_id: str | None = None
    message: str


class TradeAuditRecord(BaseModel):
    """Serializable audit record captured for each trade request as it moves through the platform."""

    symbol: str
    status: TradeLifecycleStatus
    detail: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class StrategyRunRecord(BaseModel):
    """Persistence model representing one strategy evaluation attempt for a symbol."""

    symbol: str
    timeframe: str
    short_window: int
    long_window: int
    action: SignalAction
    confidence: float
    reason: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class TradeOrderRecord(BaseModel):
    """Persistence model representing one broker or simulated order generated by the platform."""

    symbol: str
    action: SignalAction
    quantity: int
    status: OrderStatus
    requested_price: float
    broker_order_id: str | None = None
    dry_run: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)


class PositionRecord(BaseModel):
    """Persistence model that tracks the internal position view after execution."""

    symbol: str
    side: PositionSide
    quantity: int
    average_price: float
    metadata: dict[str, Any] = Field(default_factory=dict)


class TradeAuditLogRead(BaseModel):
    """API model returned when operators query persisted trade audit events."""

    id: int
    symbol: str
    status: str
    detail: str
    metadata: dict[str, Any]
    created_at: datetime


class StrategyRunRead(BaseModel):
    """API model returned when operators query persisted strategy evaluation history."""

    id: int
    symbol: str
    timeframe: str
    short_window: int
    long_window: int
    action: str
    confidence: float
    reason: str
    metadata: dict[str, Any]
    created_at: datetime


class TradeOrderRead(BaseModel):
    """API model returned when operators query persisted order history."""

    id: int
    symbol: str
    action: str
    quantity: int
    status: str
    requested_price: float
    broker_order_id: str | None
    dry_run: bool
    metadata: dict[str, Any]
    created_at: datetime


class PositionRead(BaseModel):
    """API model returned when operators query the internal position snapshot."""

    id: int
    symbol: str
    side: str
    quantity: int
    average_price: float
    metadata: dict[str, Any]
    updated_at: datetime


class TradeAuditLogListResponse(BaseModel):
    """Paginated response returned for trade audit log queries."""

    total: int
    limit: int
    offset: int
    items: list[TradeAuditLogRead]


class StrategyRunListResponse(BaseModel):
    """Paginated response returned for strategy-run queries."""

    total: int
    limit: int
    offset: int
    items: list[StrategyRunRead]


class TradeOrderListResponse(BaseModel):
    """Paginated response returned for trade-order queries."""

    total: int
    limit: int
    offset: int
    items: list[TradeOrderRead]


class PositionListResponse(BaseModel):
    """Response returned for position queries."""

    total: int
    items: list[PositionRead]


class TradeSignalResponse(BaseModel):
    """Composite API response that exposes strategy, risk, and execution outcomes together."""

    symbol: str
    decision: StrategyDecision
    risk_approved: bool
    execution: ExecutionResult
